# Generated by Django 5.0.6 on 2024-06-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joingroupmodel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
