# Generated by Django 5.0.6 on 2024-06-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0003_joingroupmodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joingroupmodel',
            name='otp',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
