# Generated by Django 5.0.6 on 2024-06-27 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0004_alter_joingroupmodel_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.TextField(max_length=50)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task2.groupmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='JoinGroupModel',
        ),
    ]
