# Generated by Django 5.0.6 on 2024-06-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0006_alter_groupmembermodel_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.TextField(max_length=50)),
            ],
        ),
    ]
