# Generated by Django 5.0.6 on 2024-06-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0008_groupmembermodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembermodel',
            name='user_email',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmembermodel',
            name='username',
            field=models.TextField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='name',
            field=models.TextField(max_length=50, unique=True),
        ),
    ]
