# Generated by Django 5.0.6 on 2024-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0009_alter_groupmembermodel_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmembermodel',
            name='user_email',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='groupmembermodel',
            name='username',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='groupmembermodel',
            unique_together={('user_email', 'group_id', 'username')},
        ),
    ]
