# Generated by Django 5.0.6 on 2024-07-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0010_alter_groupmembermodel_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.IntegerField(max_length=50),
        ),
    ]
