# Generated by Django 5.0.6 on 2024-07-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0011_alter_otpmodel_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='otp',
            field=models.IntegerField(),
        ),
    ]
