# Generated by Django 5.0.6 on 2024-07-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0012_alter_otpmodel_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpmodel',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
